// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { resolve } from "node:path";
import { defineConfig } from "prisma/config";

function resolveDatasourceUrl(rawUrl?: string) {
  if (!rawUrl) {
    return rawUrl;
  }

  if (!rawUrl.startsWith("file:")) {
    return rawUrl;
  }

  const filePath = rawUrl.replace("file:", "");

  if (
    filePath === ":memory:" ||
    filePath.startsWith("/") ||
    /^[a-zA-Z]:\//.test(filePath) ||
    /^[a-zA-Z]:\\/.test(filePath)
  ) {
    return rawUrl;
  }

  const normalized = resolve(process.cwd(), "prisma", filePath.replace(/^\.?[\\/]/, ""));
  return `file:${normalized.replace(/\\/g, "/")}`;
}

export default defineConfig({
  schema: process.env["PRISMA_SCHEMA_PATH"] ?? "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: resolveDatasourceUrl(process.env["DATABASE_URL"]),
  },
});
